"use client";

import { useState } from "react";
import { STAGES, STAGE_LABELS, STAGE_HINTS } from "@/lib/stages";
import { stageProgress, type VideoDTO } from "@/lib/types";

export default function StudioOverview({ videos, onOpen, onCreate, creating }: { videos: VideoDTO[]; onOpen: (id: string) => void; onCreate: (title: string, description: string) => Promise<boolean>; creating: boolean }) {
  const [title, setTitle] = useState("");
  const [description, setDescription] = useState("");
  const [saving, setSaving] = useState(false);
  const active = videos.filter(v => v.stage !== "POSTADO");
  const scheduled = active.filter(v => v.publishAt).sort((a,b) => Date.parse(a.publishAt!) - Date.parse(b.publishAt!));
  const current = active.filter(v => !["IDEIA", "AGENDADO"].includes(v.stage)).sort((a,b) => STAGES.indexOf(b.stage) - STAGES.indexOf(a.stage));
  const next = current[0] ?? scheduled[0] ?? active[0];
  const published = videos.filter(v => v.stage === "POSTADO");
  const date = (value: string) => new Intl.DateTimeFormat("pt-BR", { day:"numeric", month:"short", hour:"2-digit", minute:"2-digit", timeZone:"Europe/London" }).format(new Date(value));
  return <main className="studio-overview">
    <section className="studio-hero"><div><span className="studio-kicker">SEU ESTÚDIO PESSOAL · @KAUAARTX</span><h1>Uma ideia sua.<br /><em>Uma história para contar.</em></h1><p>Escolha uma produção para continuar. O restante fica guardado até a hora certa.</p><a href="https://studio.youtube.com/" target="_blank" rel="noopener noreferrer">Abrir YouTube Studio ↗</a></div><div className="studio-feature"><span>PRÓXIMA PRODUÇÃO</span>{next ? <><small>{STAGE_LABELS[next.stage]}</small><h2>{next.title}</h2><p>{next.checklistItems.find(i => i.stage === next.stage && !i.done)?.text ?? STAGE_HINTS[next.stage]}</p><button onClick={() => onOpen(next.id)}>Continuar este vídeo →</button></> : <><h2>Qual história você quer contar?</h2><p>Guarde uma ideia abaixo. O roteiro e os próximos passos ficam juntos no mesmo vídeo.</p><a href="#capture-idea">Anotar minha primeira ideia ↓</a></>}</div></section>
    <div className="studio-stats"><div><strong>{videos.filter(v => v.stage === "IDEIA").length}</strong><span>ideias guardadas</span></div><div><strong>{current.length}</strong><span>em produção</span></div><div><strong>{videos.filter(v => v.stage === "AGENDADO").length}</strong><span>na etapa agendado</span></div><div><strong>{published.length}</strong><span>marcados como postados</span></div></div>
    <div className="studio-grid"><section className="studio-panel"><span className="studio-kicker">MANTENHA O FIO</span><h2>Na sua mesa de edição</h2><p className="studio-muted">Primeiro os vídeos mais avançados no fluxo.</p>{current.slice(0,5).map(video => { const progress=stageProgress(video); return <button className="studio-row" key={video.id} onClick={() => onOpen(video.id)}><span><small>{STAGE_LABELS[video.stage]}</small><strong>{video.title}</strong><span>{video.checklistItems.find(i => i.stage === video.stage && !i.done)?.text ?? 'Abrir e revisar o próximo passo'}</span></span><span>{progress.done}/{progress.total}<br />→</span></button>; })}{!current.length && <p className="studio-empty">Nenhum vídeo em produção. Abra uma ideia e avance para o roteiro quando quiser começar.</p>}</section>
    <section className="studio-panel"><span className="studio-kicker">AGENDA EDITORIAL</span><h2>Datas que você planejou</h2><p className="studio-muted">Horários de Londres. Este planejamento não agenda vídeos no YouTube.</p>{scheduled.slice(0,5).map(video => <button className="studio-row" key={video.id} onClick={() => onOpen(video.id)}><span><small>{date(video.publishAt!)}</small><strong>{video.finalTitle || video.title}</strong><span>{STAGE_LABELS[video.stage]}</span></span><span>→</span></button>)}{!scheduled.length && <p className="studio-empty">Sem datas definidas. Você pode escolher uma na etapa Agendado de cada vídeo.</p>}</section></div>
    <div className="studio-grid"><section className="studio-panel" id="capture-idea"><span className="studio-kicker">CAPTURA RÁPIDA</span><h2>Guarde antes de esquecer</h2><form className="studio-form" onSubmit={async e => { e.preventDefault(); if(saving) return; setSaving(true); try { if(await onCreate(title,description)){setTitle("");setDescription("");} } finally { setSaving(false); } }}><label>Ideia ou título provisório<input required maxLength={300} value={title} onChange={e => setTitle(e.target.value)} placeholder="Uma história que quero contar…" /></label><label>O que acontece nesse vídeo?<textarea maxLength={5000} rows={3} value={description} onChange={e => setDescription(e.target.value)} placeholder="Uma situação, uma pergunta e o que quero mostrar." /></label><button disabled={creating || saving || !title.trim()}>{creating || saving ? "Guardando…" : "Guardar ideia e abrir →"}</button></form></section>
    <section className="studio-panel"><span className="studio-kicker">SEU PROCESSO</span><h2>Da ideia ao aprendizado</h2><ol className="studio-process"><li><strong>Defina a história.</strong> Qual pergunta o vídeo responde? Anote o gancho e suas referências.</li><li><strong>Prepare e produza.</strong> Divida o roteiro em trechos, grave e acompanhe cada bloco na edição.</li><li><strong>Embale e revise.</strong> Escolha título e thumbnail; confira o vídeo inteiro antes de publicar.</li><li><strong>Guarde o que aprendeu.</strong> Depois da publicação, registre o que repetir e o que mudar.</li></ol>{published.filter(v=>v.learnings.trim()).slice(0,2).map(v=><button key={v.id} className="studio-row" onClick={()=>onOpen(v.id)}><span><small>APRENDIZADO GUARDADO</small><strong>{v.title}</strong><span>{v.learnings.slice(0,150)}{v.learnings.length>150 ? '…' : ''}</span></span><span>↗</span></button>)}</section></div>
  </main>;
}
