"use client";

import { useState } from "react";
import { STAGES, STAGE_LABELS, STAGE_HINTS } from "@/lib/stages";
import { stageProgress, type VideoDTO } from "@/lib/types";
import { useI18n } from "./I18n";

export default function StudioOverview({ videos, onOpen, onCreate, creating }: { videos: VideoDTO[]; onOpen: (id: string) => void; onCreate: (title: string, description: string) => Promise<boolean>; creating: boolean }) {
  const { t, locale } = useI18n();
  const [title, setTitle] = useState("");
  const [description, setDescription] = useState("");
  const [saving, setSaving] = useState(false);
  const active = videos.filter(v => v.stage !== "POSTADO");
  const scheduled = active.filter(v => v.publishAt).sort((a,b) => Date.parse(a.publishAt!) - Date.parse(b.publishAt!));
  const current = active.filter(v => !["IDEIA", "AGENDADO"].includes(v.stage)).sort((a,b) => STAGES.indexOf(b.stage) - STAGES.indexOf(a.stage));
  const next = current[0] ?? scheduled[0] ?? active[0];
  const published = videos.filter(v => v.stage === "POSTADO");
  const date = (value: string) => new Intl.DateTimeFormat(locale, { day:"numeric", month:"short", hour:"2-digit", minute:"2-digit", timeZone:"Europe/London" }).format(new Date(value));
  return <main className="studio-overview">
    <section className="studio-hero"><div><span className="studio-kicker">{t("SEU ESTÚDIO PESSOAL · @KAUAARTX")}</span><h1>{t("Uma ideia sua.")}<br /><em>{t("Uma história para contar.")}</em></h1><p>{t("Escolha uma produção para continuar. O restante fica guardado até a hora certa.")}</p><a href="https://studio.youtube.com/" target="_blank" rel="noopener noreferrer">{t("Abrir YouTube Studio ↗")}</a></div><div className="studio-feature"><span>{t("PRÓXIMA PRODUÇÃO")}</span>{next ? <><small>{t(STAGE_LABELS[next.stage])}</small><h2>{t(next.title)}</h2><p>{t(next.checklistItems.find(i => i.stage === next.stage && !i.done)?.text) ?? t(STAGE_HINTS[next.stage])}</p><button onClick={() => onOpen(next.id)}>{t("Continuar este vídeo →")}</button></> : <><h2>{t("Qual história você quer contar?")}</h2><p>{t("Guarde uma ideia abaixo. O roteiro e os próximos passos ficam juntos no mesmo vídeo.")}</p><a href="#capture-idea">{t("Anotar minha primeira ideia ↓")}</a></>}</div></section>
    <div className="studio-stats"><div><strong>{t(videos.filter(v => v.stage === "IDEIA").length)}</strong><span>{t("ideias guardadas")}</span></div><div><strong>{t(current.length)}</strong><span>{t("em produção")}</span></div><div><strong>{t(videos.filter(v => v.stage === "AGENDADO").length)}</strong><span>{t("na etapa agendado")}</span></div><div><strong>{t(published.length)}</strong><span>{t("marcados como postados")}</span></div></div>
    <div className="studio-grid"><section className="studio-panel"><span className="studio-kicker">{t("MANTENHA O FIO")}</span><h2>{t("Na sua mesa de edição")}</h2><p className="studio-muted">{t("Primeiro os vídeos mais avançados no fluxo.")}</p>{current.slice(0,5).map(video => { const progress=stageProgress(video); return <button className="studio-row" key={video.id} onClick={() => onOpen(video.id)}><span><small>{t(STAGE_LABELS[video.stage])}</small><strong>{t(video.title)}</strong><span>{t(video.checklistItems.find(i => i.stage === video.stage && !i.done)?.text) ?? t("Abrir e revisar o próximo passo")}</span></span><span>{t(progress.done)}/{t(progress.total)}<br />→</span></button>; })}{!current.length && <p className="studio-empty">{t("Nenhum vídeo em produção. Abra uma ideia e avance para o roteiro quando quiser começar.")}</p>}</section>
    <section className="studio-panel"><span className="studio-kicker">{t("AGENDA EDITORIAL")}</span><h2>{t("Datas que você planejou")}</h2><p className="studio-muted">{t("Horários de Londres. Este planejamento não agenda vídeos no YouTube.")}</p>{scheduled.slice(0,5).map(video => <button className="studio-row" key={video.id} onClick={() => onOpen(video.id)}><span><small>{date(video.publishAt!)}</small><strong>{video.finalTitle || video.title}</strong><span>{t(STAGE_LABELS[video.stage])}</span></span><span>→</span></button>)}{!scheduled.length && <p className="studio-empty">{t("Sem datas definidas. Você pode escolher uma na etapa Agendado de cada vídeo.")}</p>}</section></div>
    <div className="studio-grid"><section className="studio-panel" id="capture-idea"><span className="studio-kicker">{t("CAPTURA RÁPIDA")}</span><h2>{t("Guarde antes de esquecer")}</h2><form className="studio-form" onSubmit={async e => { e.preventDefault(); if(saving) return; setSaving(true); try { if(await onCreate(title,description)){setTitle("");setDescription("");} } finally { setSaving(false); } }}><label>{t("Ideia ou título provisório")}<input required maxLength={300} value={title} onChange={e => setTitle(e.target.value)} placeholder={t("Uma história que quero contar…")} /></label><label>{t("O que acontece nesse vídeo?")}<textarea maxLength={5000} rows={3} value={description} onChange={e => setDescription(e.target.value)} placeholder={t("Uma situação, uma pergunta e o que quero mostrar.")} /></label><button disabled={creating || saving || !title.trim()}>{creating || saving ? t("Guardando…") : t("Guardar ideia e abrir →")}</button></form></section>
    <section className="studio-panel"><span className="studio-kicker">{t("SEU PROCESSO")}</span><h2>{t("Da ideia ao aprendizado")}</h2><ol className="studio-process"><li><strong>{t("Defina a história.")}</strong>{t(" Qual pergunta o vídeo responde? Anote o gancho e suas referências.")}</li><li><strong>{t("Prepare e produza.")}</strong>{t(" Divida o roteiro em trechos, grave e acompanhe cada bloco na edição.")}</li><li><strong>{t("Embale e revise.")}</strong>{t(" Escolha título e thumbnail; confira o vídeo inteiro antes de publicar.")}</li><li><strong>{t("Guarde o que aprendeu.")}</strong>{t(" Depois da publicação, registre o que repetir e o que mudar.")}</li></ol>{published.filter(v=>v.learnings.trim()).slice(0,2).map(v=><button key={v.id} className="studio-row" onClick={()=>onOpen(v.id)}><span><small>{t("APRENDIZADO GUARDADO")}</small><strong>{t(v.title)}</strong><span>{v.learnings.slice(0,150)}{v.learnings.length>150 ? '…' : ''}</span></span><span>↗</span></button>)}</section></div>
  </main>;
}
